import { defineConfig } from 'eslint/config';

export = defineConfig({
    rules: {
        'arrow-body-style': ['warn', 'as-needed'],
        '@stylistic/arrow-parens': 'off',
        '@stylistic/arrow-spacing': 'warn',
        'constructor-super': 'error',
        '@stylistic/generator-star-spacing': 'off',
        'no-class-assign': 'error',
        '@stylistic/no-confusing-arrow': 'off',
        'no-const-assign': 'error',
        'no-dupe-class-members': 'error',
        'no-duplicate-imports': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-restricted-exports': 'off',
        'no-restricted-imports': 'off',
        'no-this-before-super': 'error',
        'no-useless-computed-key': 'off',
        'no-useless-constructor': 'warn',
        'no-useless-rename': 'warn',
        'no-var': 'off',
        'object-shorthand': ['warn', 'always', {
            avoidQuotes: true,
            ignoreConstructors: true,
            avoidExplicitReturnArrows: true,
        }],
        'prefer-arrow-callback': 'warn',
        'prefer-const': 'warn',
        'prefer-destructuring': [
            'warn',
            {
                VariableDeclarator: {
                    array: false,
                    object: true,
                },
            },
        ],
        'prefer-numeric-literals': 'off',
        'prefer-rest-params': 'warn',
        'prefer-spread': 'warn',
        'prefer-template': 'warn',
        'require-yield': 'off',
        '@stylistic/rest-spread-spacing': 'warn',
        'sort-imports': 'off',
        'symbol-description': 'off',
        '@stylistic/template-curly-spacing': 'warn',
        '@stylistic/yield-star-spacing': 'off',
        'prefer-object-has-own': 'warn',
    },
});
