module.exports = {
    rules: {
        'array-bracket-newline': 'off',
        'array-bracket-spacing': 'warn',
        'array-element-newline': 'off',
        'block-spacing': 'warn',
        'brace-style': 'off',
        camelcase: 'warn',
        'capitalized-comments': 'off',
        'comma-dangle': [
            'warn',
            {
                arrays: 'always-multiline',
                objects: 'always-multiline',
                imports: 'always-multiline',
                exports: 'always-multiline',
                functions: 'always-multiline',
            },
        ],
        'comma-spacing': 'warn',
        'comma-style': 'warn',
        'computed-property-spacing': 'warn',
        'consistent-this': 'off',
        'eol-last': 'warn',
        'func-call-spacing': 'warn',
        'func-name-matching': 'warn',
        'func-names': 'warn',
        'func-style': 'off',
        'function-call-argument-newline': ['warn', 'consistent'],
        'function-paren-newline': 'off',
        'grouped-accessor-pairs': 'warn',
        'id-blacklist': 'off',
        'id-length': 'off',
        'id-match': 'off',
        'implicit-arrow-linebreak': 'off',
        indent: ['warn', 4, { SwitchCase: 1 }],
        'jsx-quotes': ['warn', 'prefer-double'],
        'key-spacing': 'warn',
        'keyword-spacing': 'warn',
        'line-comment-position': 'off',
        'linebreak-style': 'off',
        'lines-around-comment': 'off',
        'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
        'max-depth': 'off',
        'max-len': ['warn', 140, 4],
        'max-lines': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        'max-statements-per-line': 'off',
        'multiline-comment-style': 'off',
        'multiline-ternary': 'off',
        'new-cap': 'off',
        'new-parens': 'off',
        'newline-per-chained-call': ['warn', { ignoreChainWithDepth: 3 }],
        'no-array-constructor': 'error',
        'no-bitwise': 'off',
        'no-continue': 'off',
        'no-inline-comments': 'off',
        'no-lonely-if': 'error',
        'no-mixed-operators': 'off',
        'no-mixed-spaces-and-tabs': 'warn',
        'no-multi-assign': 'off',
        'no-multiple-empty-lines': ['warn', { max: 1 }],
        'no-negated-condition': 'warn',
        'no-nested-ternary': 'warn',
        'no-new-object': 'error',
        'no-plusplus': 'off',
        'no-restricted-syntax': 'off',
        'no-tabs': 'warn',
        'no-ternary': 'off',
        'no-trailing-spaces': 'warn',
        'no-underscore-dangle': 'off',
        'no-unneeded-ternary': 'warn',
        'no-whitespace-before-property': 'warn',
        'nonblock-statement-body-position': 'off',
        'object-curly-newline': 'off',
        'object-curly-spacing': ['warn', 'always'],
        'object-property-newline': 'off',
        'one-var': ['warn', { var: 'always', let: 'never', const: 'never' }],
        'one-var-declaration-per-line': 'off',
        'operator-assignment': 'off',
        'operator-linebreak': 'off',
        'padded-blocks': ['warn', { blocks: 'never', classes: 'always', switches: 'never' }],
        'padding-line-between-statements': 'off',
        'prefer-exponentiation-operator': 'off',
        'quote-props': ['warn', 'as-needed'],
        quotes: [
            'warn',
            'single',
            {
                avoidEscape: true,
            },
        ],
        semi: ['warn', 'always'],
        'semi-spacing': 'warn',
        'semi-style': 'off',
        'sort-keys': 'off',
        'sort-vars': 'off',
        'space-before-blocks': 'warn',
        'space-before-function-paren': ['warn', { anonymous: 'always', named: 'never' }],
        'space-in-parens': 'warn',
        'space-infix-ops': 'off',
        'space-unary-ops': 'off',
        'spaced-comment': 'off',
        'switch-colon-spacing': 'off',
        'template-tag-spacing': 'warn',
        'unicode-bom': 'off',
        'wrap-regex': 'off',
    },
};
