import { defineConfig } from 'eslint/config';

export = defineConfig({
    rules: {
        '@stylistic/array-bracket-newline': 'off',
        '@stylistic/array-bracket-spacing': 'warn',
        '@stylistic/array-element-newline': 'off',
        '@stylistic/block-spacing': 'warn',
        '@stylistic/brace-style': 'off',
        camelcase: 'warn',
        'capitalized-comments': 'off',
        '@stylistic/comma-dangle': [
            'warn',
            {
                arrays: 'always-multiline',
                objects: 'always-multiline',
                imports: 'always-multiline',
                exports: 'always-multiline',
                functions: 'always-multiline',
                enums: 'always-multiline',
                generics: 'always-multiline',
                tuples: 'always-multiline',
            },
        ],
        '@stylistic/comma-spacing': 'warn',
        '@stylistic/comma-style': 'warn',
        '@stylistic/computed-property-spacing': 'warn',
        'consistent-this': 'off',
        '@stylistic/eol-last': 'warn',
        '@stylistic/function-call-spacing': 'warn',
        'func-name-matching': 'warn',
        'func-names': 'warn',
        'func-style': 'off',
        '@stylistic/function-call-argument-newline': ['warn', 'consistent'],
        '@stylistic/function-paren-newline': 'off',
        'grouped-accessor-pairs': 'warn',
        'id-denylist': 'off',
        'id-length': 'off',
        'id-match': 'off',
        '@stylistic/implicit-arrow-linebreak': 'off',
        '@stylistic/indent': ['warn', 4, { SwitchCase: 1 }],
        '@stylistic/jsx-quotes': ['warn', 'prefer-double'],
        '@stylistic/key-spacing': 'warn',
        '@stylistic/keyword-spacing': 'warn',
        '@stylistic/line-comment-position': 'off',
        '@stylistic/linebreak-style': 'off',
        '@stylistic/lines-around-comment': 'off',
        '@stylistic/lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
        'max-depth': 'off',
        '@stylistic/max-len': ['warn', 140, 4],
        'max-lines': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        '@stylistic/max-statements-per-line': 'off',
        '@stylistic/multiline-comment-style': 'off',
        '@stylistic/multiline-ternary': 'off',
        'new-cap': 'off',
        '@stylistic/new-parens': 'off',
        '@stylistic/newline-per-chained-call': ['warn', { ignoreChainWithDepth: 3 }],
        'no-array-constructor': 'error',
        'no-bitwise': 'off',
        'no-continue': 'off',
        'no-inline-comments': 'off',
        'no-lonely-if': 'error',
        '@stylistic/no-mixed-operators': 'off',
        '@stylistic/no-mixed-spaces-and-tabs': 'warn',
        'no-multi-assign': 'off',
        '@stylistic/no-multiple-empty-lines': ['warn', { max: 1 }],
        'no-negated-condition': 'warn',
        'no-nested-ternary': 'warn',
        'no-object-constructor': 'error',
        'no-plusplus': 'off',
        'no-restricted-syntax': 'off',
        '@stylistic/no-tabs': 'warn',
        'no-ternary': 'off',
        '@stylistic/no-trailing-spaces': 'warn',
        'no-underscore-dangle': 'off',
        'no-unneeded-ternary': 'warn',
        '@stylistic/no-whitespace-before-property': 'warn',
        '@stylistic/nonblock-statement-body-position': 'off',
        '@stylistic/object-curly-newline': 'off',
        '@stylistic/object-curly-spacing': ['warn', 'always'],
        '@stylistic/object-property-newline': 'off',
        'one-var': ['warn', { var: 'always', let: 'never', const: 'never' }],
        '@stylistic/one-var-declaration-per-line': 'off',
        'operator-assignment': 'off',
        '@stylistic/operator-linebreak': 'off',
        '@stylistic/padded-blocks': ['warn', { blocks: 'never', classes: 'always', switches: 'never' }],
        '@stylistic/padding-line-between-statements': 'off',
        'prefer-exponentiation-operator': 'off',
        '@stylistic/quote-props': ['warn', 'as-needed'],
        '@stylistic/quotes': [
            'warn',
            'single',
            {
                avoidEscape: true,
            },
        ],
        '@stylistic/semi': ['warn', 'always'],
        '@stylistic/semi-spacing': 'warn',
        '@stylistic/semi-style': 'off',
        'sort-keys': 'off',
        'sort-vars': 'off',
        '@stylistic/space-before-blocks': 'warn',
        '@stylistic/space-before-function-paren': ['warn', { anonymous: 'always', named: 'never' }],
        '@stylistic/space-in-parens': 'warn',
        '@stylistic/space-infix-ops': 'off',
        '@stylistic/space-unary-ops': 'off',
        '@stylistic/spaced-comment': 'off',
        '@stylistic/switch-colon-spacing': 'off',
        '@stylistic/template-tag-spacing': 'warn',
        'unicode-bom': 'off',
        '@stylistic/wrap-regex': 'off',
    },
});
