sudo: false
dist: trusty

language: node_js
node_js:
- "10"
- "9"

cache:
  directories:
  - "node_modules"

jobs:
  include:
  - stage: test
    name: test
    script: npm test
  - stage: deploy
    name: npm
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      tag: latest
      on:
        tags: true
stages:
- test
- name: deploy
  if: tag IS present
