module.exports = {
    rules: {
        // Enforce “for” loop update clause moving the counter in the right direction
        // http://eslint.org/docs/rules/for-direction
        'for-direction': 'error',

        // Enforces that a return statement is present in property getters
        // http://eslint.org/docs/rules/getter-return
        'getter-return': ['error', { allowImplicit: true }],
        'no-await-in-loop': 'warn',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-console': 'error',
        'no-constant-condition': 'off',
        'no-control-regex': 'off',
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': ['warn', { allowEmptyCatch: true }],
        'no-empty-character-class': 'warn',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'warn',
        'no-extra-parens': 'off',
        'no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-import-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'warn',
        'no-irregular-whitespace': ['warn', { skipStrings: true }],
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-obj-calls': 'error',
        'no-promise-executor-return': 'error',
        'no-prototype-builtins': 'off',
        'no-regex-spaces': 'off',
        'no-setter-return': 'error',
        'no-sparse-arrays': 'warn',
        'no-template-curly-in-string': 'error',
        'no-unexpected-multiline': 'warn',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'off',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-useless-backreference': 'warn',
        'require-atomic-updates': 'warn',
        'require-unicode-regexp': 'off',
        'use-isnan': 'error',
        'valid-typeof': 'error',
    },
};
