module.exports = {
    env: {
        es6: true,
    },
    parserOptions: {
        ecmaVersion: 11,
        sourceType: 'module',
        ecmaFeatures: {
            generators: false,
            objectLiteralDuplicateProperties: false,
        },
    },
    rules: {
        'arrow-body-style': ['warn', 'as-needed'],
        'arrow-parens': ['off'],
        'arrow-spacing': ['warn'],
        'constructor-super': ['error'],
        'generator-star-spacing': ['off'],
        'no-class-assign': ['error'],
        'no-confusing-arrow': ['off'],
        'no-const-assign': ['error'],
        'no-dupe-class-members': ['error'],
        'no-duplicate-imports': ['error'],
        'no-new-symbol': ['error'],
        'no-restricted-exports': ['off'],
        'no-restricted-imports': ['off'],
        'no-this-before-super': ['error'],
        'no-useless-computed-key': ['off'],
        'no-useless-constructor': ['off'],
        'no-useless-rename': ['off'],
        'no-var': ['off'],
        'object-shorthand': ['off'],
        'prefer-arrow-callback': ['warn'],
        'prefer-const': ['warn'],
        'prefer-destructuring': ['warn', { array: false, object: true }],
        'prefer-numeric-literals': ['off'],
        'prefer-rest-params': ['warn'],
        'prefer-spread': ['warn'],
        'prefer-template': ['warn'],
        'require-yield': ['off'],
        'rest-spread-spacing': ['warn'],
        'sort-imports': ['off'],
        'symbol-description': ['off'],
        'template-curly-spacing': ['warn'],
        'yield-star-spacing': ['off'],
    },
};
